import type { Agency, ItineraryTemplate, Trip, Worker } from '../types';

export const INITIAL_ITINERARY_TEMPLATES: ItineraryTemplate[] = [
  {
    id: 'tmpl-bromo-sunrise',
    name: 'Bromo Sunrise Golden Hour (4 Spot)',
    category: 'Bromo Adventure',
    duration: '7 Jam (03:00 - 10:00 WIB)',
    description: 'Rute klasik sunrise Penanjakan 1, Kawah Bromo, Pasir Berbisik, dan Bukit Teletubbies.',
    defaultPrice: 1250000,
    items: [
      {
        time: '03:00 WIB',
        title: 'Penjemputan Tamu & Briefing',
        location: 'Lobby Hotel / Homestay',
        description: 'Pengecekan perlengkapan dingin, jaket, dan masker tamu.',
        operationalCost: 0,
        costNote: 'Briefing internal',
      },
      {
        time: '04:15 WIB',
        title: 'Sunrise View Point Penanjakan 1',
        location: 'Puncak Penanjakan 1 Bromo',
        description: 'Menikmati golden sunrise dengan latar Gunung Batok & Semeru.',
        operationalCost: 110000,
        costNote: 'Tiket Masuk TNBTS & Retribusi Pemkab',
      },
      {
        time: '06:30 WIB',
        title: 'Kawah Aktif Bromo & Pura Luhur Poten',
        location: 'Lautan Pasir & Tangga Kawah',
        description: 'Trekking menuju bibir kawah aktif Bromo (opsi naik kuda mandiri).',
        operationalCost: 20000,
        costNote: 'Retribusi Parkir Armada Lautan Pasir',
      },
      {
        time: '08:30 WIB',
        title: 'Pasir Berbisik & Bukit Teletubbies (Savana)',
        location: 'Savana Hijau Lembah Jemplang',
        description: 'Sesi dokumentasi foto dan eksplorasi padang savana.',
        operationalCost: 50000,
        costNote: 'Bahan Bakar Minyak (BBM) Jeep Operasional',
      },
      {
        time: '10:00 WIB',
        title: 'Pengantaran Kembali ke Pos / Hotel',
        location: 'Hotel Tamu / Basecamp Sukapura',
        description: 'Tour selesai, serah terima tamu untuk istirahat atau shuttle.',
        operationalCost: 0,
        costNote: 'Rute kepulangan',
      }
    ]
  },
  {
    id: 'tmpl-bromo-sunset',
    name: 'Bromo Sunset Adventure & Milky Way VIP',
    category: 'Bromo Special',
    duration: '8 Jam (14:00 - 22:00 WIB)',
    description: 'Eksplorasi sore hari di Bukit Cinta dilanjutkan pemotretan bintang galaksi (Milky Way).',
    defaultPrice: 1500000,
    items: [
      {
        time: '14:00 WIB',
        title: 'Penjemputan Tamu & Persiapan Alat',
        location: 'Resort / Homestay Bromo',
        description: 'Pengecekan peralatan fotografi malam, tripod, dan drone.',
        operationalCost: 0,
        costNote: 'Briefing tim',
      },
      {
        time: '15:30 WIB',
        title: 'Savana Teletubbies & Wisata Bunga Edelweiss',
        location: 'Savana Bromo',
        description: 'Sesi foto daylight & sore hari dengan pencahayaan alami.',
        operationalCost: 30000,
        costNote: 'Tiket spot bunga edelweiss binaan desa',
      },
      {
        time: '17:15 WIB',
        title: 'Sunset Spektakuler Bukit Cinta',
        location: 'Bukit Cinta View Point',
        description: 'Menikmati matahari terbenam dengan siluet kaldera Bromo.',
        operationalCost: 20000,
        costNote: 'Parkir armada sore',
      },
      {
        time: '18:30 WIB',
        title: 'Makan Malam Hangat Basecamp',
        location: 'Rest Area Sukapura',
        description: 'Makan malam khas Tengger dan persiapan sesi malam.',
        operationalCost: 60000,
        costNote: 'Konsumsi kru operasional & tamu VIP',
      },
      {
        time: '20:00 WIB',
        title: 'Sesi Foto Milky Way & Star Gazing',
        location: 'Lautan Pasir Bromo',
        description: 'Fotografi bintang galaksi dengan lampu sorot khusus.',
        operationalCost: 40000,
        costNote: 'Izin lokasi malam & BBM ekstra',
      }
    ]
  },
  {
    id: 'tmpl-merapi-lava',
    name: 'Merapi Lava Tour Adventure',
    category: 'Merapi Jogja',
    duration: '5 Jam (08:00 - 13:00 WIB)',
    description: 'Menjelajahi bekas erupsi Gunung Merapi dengan Jeep terbuka dan manuver Kalikuning.',
    defaultPrice: 950000,
    items: [
      {
        time: '08:00 WIB',
        title: 'Standby Basecamp & Safety Briefing',
        location: 'Basecamp Jeep Kaliurang',
        description: 'Pembagian helm pelindung dan briefing keselamatan trek bebatuan.',
        operationalCost: 0,
        costNote: 'Perlengkapan standar',
      },
      {
        time: '08:45 WIB',
        title: 'Museum Sisa Hartaku & Batu Alien',
        location: 'Dusun Petung Cangkringan',
        description: 'Melihat saksi bisu kedahsyatan awan panas erupsi 2010.',
        operationalCost: 40000,
        costNote: 'Tiket Masuk Kawasan Cagar Erupsi',
      },
      {
        time: '10:00 WIB',
        title: 'Bunker Kaliadem & Pemandangan Puncak',
        location: 'Bunker Kaliadem',
        description: 'Spot foto berlatar puncak Merapi yang megah.',
        operationalCost: 40000,
        costNote: 'Retribusi desa & pos pengamatan',
      },
      {
        time: '11:30 WIB',
        title: 'Manuver Air Kalikuning (Water Splash)',
        location: 'Sungai Kalikuning',
        description: 'Aksi off-road melintasi aliran air Kalikuning.',
        operationalCost: 50000,
        costNote: 'BBM Jeep & Cuci armada pasca-offroad',
      }
    ]
  }
];

export const INITIAL_WORKERS: Worker[] = [
  // Driver Jeep
  {
    id: 'w-jeep-1',
    name: 'Budi Santoso',
    role: 'driver_jeep',
    type: 'internal',
    phone: '0812-3344-5561',
    vehicleUnit: 'Jeep 01 (Hardtop N 1045 AB)',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    baseRatePerTrip: 250000,
    isAvailable: true,
  },
  {
    id: 'w-jeep-2',
    name: 'Pak Slamet Riyadi',
    role: 'driver_jeep',
    type: 'internal',
    phone: '0813-2211-9988',
    vehicleUnit: 'Jeep 04 (Hardtop N 7182 XY)',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80',
    baseRatePerTrip: 250000,
    isAvailable: true,
  },
  {
    id: 'w-jeep-3',
    name: 'Joko Waluyo (Mitra Luar)',
    role: 'driver_jeep',
    type: 'external',
    phone: '0857-4433-2211',
    vehicleUnit: 'Jeep 12 (Hardtop N 9921 KL)',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=120&auto=format&fit=crop&q=80',
    baseRatePerTrip: 300000,
    isAvailable: true,
  },
  // Driver Lapangan (Shuttle / Transfer Hotel-Pos)
  {
    id: 'w-field-1',
    name: 'Rian Hidayat',
    role: 'driver_lapangan',
    type: 'internal',
    phone: '0821-6677-8899',
    vehicleUnit: 'HiAce Shuttle 02 (N 7788 OP)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    baseRatePerTrip: 175000,
    isAvailable: true,
  },
  {
    id: 'w-field-2',
    name: 'Agus Setiawan (Sewa)',
    role: 'driver_lapangan',
    type: 'external',
    phone: '0819-3344-1122',
    vehicleUnit: 'Innova Reborn (N 1122 TR)',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    baseRatePerTrip: 200000,
    isAvailable: true,
  },
  // Fotografer Dokumentasi
  {
    id: 'w-photo-1',
    name: 'Dimas Anggara',
    role: 'photographer',
    type: 'internal',
    phone: '0812-9988-7766',
    vehicleUnit: 'Sony A7 IV + Lens Kit',
    avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=120&auto=format&fit=crop&q=80',
    baseRatePerTrip: 200000,
    isAvailable: true,
  },
  {
    id: 'w-photo-2',
    name: 'Fajar Snap (Freelance)',
    role: 'photographer',
    type: 'external',
    phone: '0878-5544-3322',
    vehicleUnit: 'Canon R6 + Drone Mini 4',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&auto=format&fit=crop&q=80',
    baseRatePerTrip: 250000,
    isAvailable: true,
  },
  // Admin
  {
    id: 'w-admin-1',
    name: 'Admin Panorama Operasional',
    role: 'admin',
    type: 'internal',
    phone: '0811-0011-2233',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    baseRatePerTrip: 0,
    isAvailable: true,
  }
];

export const INITIAL_AGENCIES: Agency[] = [
  {
    id: 'ag-1',
    name: 'Bromo Sunrise Discovery',
    code: 'BSD',
    contactPerson: 'Ibu Linda Permata',
    phone: '0812-3456-7890',
    email: 'ops@bromosunrise.com',
    address: 'Jl. Raya Bromo No. 12, Probolinggo',
    commissionRatePercent: 10,
  },
  {
    id: 'ag-2',
    name: 'Bali Nusa Tourindo',
    code: 'BNT',
    contactPerson: 'Pak Made Ariawan',
    phone: '0813-8822-1100',
    email: 'booking@balinusatour.co.id',
    address: 'Jl. Sunset Road No. 88, Kuta, Bali',
    commissionRatePercent: 12,
  },
  {
    id: 'ag-3',
    name: 'Java Heritage Travel',
    code: 'JHT',
    contactPerson: 'Ibu Kartika Sari',
    phone: '0811-7766-3322',
    email: 'tour@javaheritage.com',
    address: 'Jl. Malioboro No. 45, Yogyakarta',
    commissionRatePercent: 10,
  },
  {
    id: 'ag-direct',
    name: 'Tamu Mandiri (Direct / Walk-In)',
    code: 'DIR',
    contactPerson: 'Front Desk Panorama',
    phone: '0811-0011-2233',
    email: 'halo@panoramasuper.com',
    address: 'Basecamp Panorama Bromo',
    commissionRatePercent: 0,
  }
];

export const INITIAL_TRIPS: Trip[] = [
  // TODAY'S TRIPS (2026-09-17)
  {
    id: 'trip-01',
    code: 'PNR-260917-01',
    date: '2026-09-17',
    timeSlot: '03:30 WIB (Sunrise)',
    tourPackage: 'Bromo Sunrise Golden Hour (4 Spot)',
    pickupPoint: 'Lobby Hotel Jiwa Jawa Bromo',
    guestName: 'Mr. David Smith & Family',
    guestCount: 4,
    guestPhone: '+61 412 345 678',
    notes: 'Bawa selimut ekstra, permintaan spot Penanjakan 1',
    agencyId: 'ag-1',
    agencyName: 'Bromo Sunrise Discovery',
    packagePrice: 1250000,
    agencyPaymentStatus: 'unpaid',
    jeepDriverId: 'w-jeep-1',
    jeepDriverName: 'Budi Santoso',
    jeepUnit: 'Jeep 01 (Hardtop N 1045 AB)',
    jeepStatus: 'internal',
    jeepFee: 250000,
    jeepPayrollStatus: 'paid',
    fieldDriverId: 'w-field-1',
    fieldDriverName: 'Rian Hidayat',
    fieldDriverStatus: 'internal',
    fieldDriverFee: 175000,
    fieldPayrollStatus: 'paid',
    photographerId: 'w-photo-1',
    photographerName: 'Dimas Anggara',
    photographerStatus: 'internal',
    photographerFee: 200000,
    photographerPayrollStatus: 'paid',
    photoAlbumUrl: 'https://drive.google.com/drive/folders/panorama-bromo-davidsmith',
    itineraryTemplateId: 'tmpl-bromo-sunrise',
    itineraryTemplateName: 'Bromo Sunrise Golden Hour (4 Spot)',
    itinerary: [
      { id: 'it-1', time: '03:00 WIB', title: 'Penjemputan Hotel Jiwa Jawa', location: 'Lobby Hotel', description: 'Briefing driver & cek jaket', operationalCost: 0 },
      { id: 'it-2', time: '04:15 WIB', title: 'Sunrise Spot Penanjakan 1', location: 'Puncak Penanjakan 1', description: 'Golden hour sunrise Semeru', operationalCost: 110000, costNote: 'Tiket Masuk TNBTS 4 Pax' },
      { id: 'it-3', time: '06:30 WIB', title: 'Kawah Bromo & Pura Luhur Poten', location: 'Laut Pasir', description: 'Trek tangga kawah', operationalCost: 20000, costNote: 'Retribusi Parkir' },
      { id: 'it-4', time: '08:30 WIB', title: 'Pasir Berbisik & Savana Teletubbies', location: 'Savana Bromo', description: 'Foto jeep & savana', operationalCost: 50000, costNote: 'BBM Jeep Operasional' },
    ],
    operationalCost: 180000,
    tripStatus: 'completed',
    updatedAt: '2026-09-17T09:30:00Z',
  },
  {
    id: 'trip-02',
    code: 'PNR-260917-02',
    date: '2026-09-17',
    timeSlot: '03:30 WIB (Sunrise)',
    tourPackage: 'Bromo Sunrise & Kawah Aktif',
    pickupPoint: 'Homestay Bromo Permai Sukapura',
    guestName: 'Rombongan Ibu Ratna Hendrawan',
    guestCount: 5,
    guestPhone: '0812-8877-6655',
    notes: 'Tamu lansia 1 orang, perlu dibantu turun naik tangga kawah',
    agencyId: 'ag-2',
    agencyName: 'Bali Nusa Tourindo',
    packagePrice: 1300000,
    agencyPaymentStatus: 'unpaid',
    jeepDriverId: 'w-jeep-2',
    jeepDriverName: 'Pak Slamet Riyadi',
    jeepUnit: 'Jeep 04 (Hardtop N 7182 XY)',
    jeepStatus: 'internal',
    jeepFee: 250000,
    jeepPayrollStatus: 'unpaid',
    fieldDriverId: 'w-field-2',
    fieldDriverName: 'Agus Setiawan (Sewa)',
    fieldDriverStatus: 'external',
    fieldDriverFee: 200000,
    fieldPayrollStatus: 'unpaid',
    photographerId: 'w-photo-2',
    photographerName: 'Fajar Snap (Freelance)',
    photographerStatus: 'external',
    photographerFee: 250000,
    photographerPayrollStatus: 'unpaid',
    photoAlbumUrl: '',
    itineraryTemplateId: 'tmpl-bromo-sunrise',
    itineraryTemplateName: 'Bromo Sunrise Golden Hour (4 Spot)',
    itinerary: [
      { id: 'it-5', time: '03:15 WIB', title: 'Penjemputan Homestay Sukapura', location: 'Homestay Bromo Permai', description: 'Persiapan rombongan', operationalCost: 0 },
      { id: 'it-6', time: '04:30 WIB', title: 'Sunrise Bukit Kingkong', location: 'Bukit Kingkong Bromo', description: 'Alternatif spot sunrise nyaman lansia', operationalCost: 120000, costNote: 'Tiket Masuk TNBTS 5 Pax' },
      { id: 'it-7', time: '07:00 WIB', title: 'Kawah Bromo Dasar', location: 'Pura Luhur Poten', description: 'Menunggu di area datar', operationalCost: 20000, costNote: 'Parkir' },
      { id: 'it-8', time: '08:30 WIB', title: 'Lautan Pasir & Savana', location: 'Pasir Berbisik', description: 'Sesi santai & foto keluarga', operationalCost: 50000, costNote: 'BBM Jeep' }
    ],
    operationalCost: 190000,
    tripStatus: 'completed',
    updatedAt: '2026-09-17T07:15:00Z',
  },
  {
    id: 'trip-03',
    code: 'PNR-260917-03',
    date: '2026-09-17',
    timeSlot: '08:30 WIB (Daylight Panorama)',
    tourPackage: 'Bromo Pasir Berbisik + Bukit Teletubbies',
    pickupPoint: 'Rest Area Sukapura Malang',
    guestName: 'Tanaka & Friends (Japan Group)',
    guestCount: 6,
    guestPhone: '+81 90 1234 5678',
    notes: 'Interpreter Jepang ikut bersama rombongan',
    agencyId: 'ag-1',
    agencyName: 'Bromo Sunrise Discovery',
    packagePrice: 1400000,
    agencyPaymentStatus: 'unpaid',
    jeepDriverId: 'w-jeep-3',
    jeepDriverName: 'Joko Waluyo (Mitra Luar)',
    jeepUnit: 'Jeep 12 (Hardtop N 9921 KL)',
    jeepStatus: 'external',
    jeepFee: 300000,
    jeepPayrollStatus: 'unpaid',
    fieldDriverId: 'w-field-1',
    fieldDriverName: 'Rian Hidayat',
    fieldDriverStatus: 'internal',
    fieldDriverFee: 175000,
    fieldPayrollStatus: 'unpaid',
    photographerId: 'w-photo-1',
    photographerName: 'Dimas Anggara',
    photographerStatus: 'internal',
    photographerFee: 200000,
    photographerPayrollStatus: 'unpaid',
    photoAlbumUrl: '',
    itineraryTemplateId: 'tmpl-bromo-sunrise',
    itineraryTemplateName: 'Bromo Daylight Panorama Tour',
    itinerary: [
      { id: 'it-9', time: '08:30 WIB', title: 'Meeting Point Sukapura', location: 'Rest Area Sukapura', description: 'Temu interpreter & naik Jeep', operationalCost: 0 },
      { id: 'it-10', time: '09:30 WIB', title: 'Kawah Bromo & Pura Luhur', location: 'Kaldera Bromo', description: 'Eksplorasi geologi kawah', operationalCost: 130000, costNote: 'Tiket TNBTS Japan Guest' },
      { id: 'it-11', time: '11:30 WIB', title: 'Pasir Berbisik & Savana Teletubbies', location: 'Savana Lembah Jemplang', description: 'Sesi video drone & foto', operationalCost: 60000, costNote: 'BBM & Izin Drone' }
    ],
    operationalCost: 190000,
    tripStatus: 'completed',
    updatedAt: '2026-09-17T11:00:00Z',
  },
  {
    id: 'trip-04',
    code: 'PNR-260917-04',
    date: '2026-09-17',
    timeSlot: '14:00 WIB (Sunset Sunset View)',
    tourPackage: 'Bromo Sunset Adventure & Milkyway Prep',
    pickupPoint: 'Plataran Bromo Resort',
    guestName: 'Keluarga Bpk. Hendra Wijaya',
    guestCount: 4,
    guestPhone: '0811-3322-4411',
    notes: 'Paket VIP sunset dengan fotografer drone',
    agencyId: 'ag-direct',
    agencyName: 'Tamu Mandiri (Direct / Walk-In)',
    packagePrice: 1500000,
    agencyPaymentStatus: 'paid',
    jeepDriverId: 'w-jeep-1',
    jeepDriverName: 'Budi Santoso',
    jeepUnit: 'Jeep 01 (Hardtop N 1045 AB)',
    jeepStatus: 'internal',
    jeepFee: 250000,
    jeepPayrollStatus: 'unpaid',
    fieldDriverId: 'w-field-1',
    fieldDriverName: 'Rian Hidayat',
    fieldDriverStatus: 'internal',
    fieldDriverFee: 175000,
    fieldPayrollStatus: 'unpaid',
    photographerId: 'w-photo-2',
    photographerName: 'Fajar Snap (Freelance)',
    photographerStatus: 'external',
    photographerFee: 250000,
    photographerPayrollStatus: 'unpaid',
    photoAlbumUrl: '',
    itineraryTemplateId: 'tmpl-bromo-sunset',
    itineraryTemplateName: 'Bromo Sunset Adventure & Milky Way VIP',
    itinerary: [
      { id: 'it-12', time: '14:00 WIB', title: 'Penjemputan Plataran Bromo', location: 'Lobby Plataran', description: 'Penjemputan keluarga VIP', operationalCost: 0 },
      { id: 'it-13', time: '15:30 WIB', title: 'Savana Teletubbies Sore', location: 'Savana Bromo', description: 'Piknik teh sore & foto', operationalCost: 30000, costNote: 'Retribusi Spot' },
      { id: 'it-14', time: '17:15 WIB', title: 'Sunset Point Bukit Cinta', location: 'Bukit Cinta', description: 'Matahari terbenam', operationalCost: 20000, costNote: 'Parkir Armada' },
      { id: 'it-15', time: '19:30 WIB', title: 'Milky Way Sea of Sand', location: 'Lautan Pasir', description: 'Pemotretan bintang malam', operationalCost: 100000, costNote: 'BBM & Izin Operasi Malam' }
    ],
    operationalCost: 150000,
    tripStatus: 'in_progress',
    updatedAt: '2026-09-17T12:00:00Z',
  },

  // PAST TRIPS (2026-09-16)
  {
    id: 'trip-05',
    code: 'PNR-260916-01',
    date: '2026-09-16',
    timeSlot: '03:30 WIB (Sunrise)',
    tourPackage: 'Bromo Sunrise Golden Hour (4 Spot)',
    pickupPoint: 'Java Banana Lodge Bromo',
    guestName: 'Ms. Sarah Connor & Partner',
    guestCount: 2,
    guestPhone: '+44 7700 900077',
    agencyId: 'ag-3',
    agencyName: 'Java Heritage Travel',
    packagePrice: 1150000,
    agencyPaymentStatus: 'paid',
    jeepDriverId: 'w-jeep-1',
    jeepDriverName: 'Budi Santoso',
    jeepUnit: 'Jeep 01 (Hardtop N 1045 AB)',
    jeepStatus: 'internal',
    jeepFee: 250000,
    jeepPayrollStatus: 'paid',
    fieldDriverId: 'w-field-1',
    fieldDriverName: 'Rian Hidayat',
    fieldDriverStatus: 'internal',
    fieldDriverFee: 175000,
    fieldPayrollStatus: 'paid',
    photographerId: 'w-photo-1',
    photographerName: 'Dimas Anggara',
    photographerStatus: 'internal',
    photographerFee: 200000,
    photographerPayrollStatus: 'paid',
    photoAlbumUrl: 'https://drive.google.com/drive/folders/panorama-sarah-connor',
    itineraryTemplateId: 'tmpl-bromo-sunrise',
    itineraryTemplateName: 'Bromo Sunrise Golden Hour (4 Spot)',
    itinerary: [
      { id: 'it-16', time: '03:30 WIB', title: 'Pickup Java Banana Lodge', location: 'Hotel', description: 'Standby tamu', operationalCost: 0 },
      { id: 'it-17', time: '04:30 WIB', title: 'Sunrise Penanjakan', location: 'Penanjakan 1', description: 'Golden sunrise', operationalCost: 100000, costNote: 'Tiket TNBTS 2 Pax' },
      { id: 'it-18', time: '07:00 WIB', title: 'Kawah & Laut Pasir', location: 'Kawah Bromo', description: 'Eksplorasi kawah', operationalCost: 50000, costNote: 'BBM & Parkir' }
    ],
    operationalCost: 150000,
    tripStatus: 'completed',
    updatedAt: '2026-09-16T10:00:00Z',
  },
  {
    id: 'trip-06',
    code: 'PNR-260916-02',
    date: '2026-09-16',
    timeSlot: '03:30 WIB (Sunrise)',
    tourPackage: 'Bromo Sunrise Classic 4 Spot',
    pickupPoint: 'Stasiun Kota Baru Malang',
    guestName: 'PT. Maju Bersama Outing (Group A)',
    guestCount: 6,
    guestPhone: '0812-4433-2211',
    agencyId: 'ag-2',
    agencyName: 'Bali Nusa Tourindo',
    packagePrice: 1350000,
    agencyPaymentStatus: 'paid',
    jeepDriverId: 'w-jeep-2',
    jeepDriverName: 'Pak Slamet Riyadi',
    jeepUnit: 'Jeep 04 (Hardtop N 7182 XY)',
    jeepStatus: 'internal',
    jeepFee: 250000,
    jeepPayrollStatus: 'paid',
    fieldDriverId: 'w-field-2',
    fieldDriverName: 'Agus Setiawan (Sewa)',
    fieldDriverStatus: 'external',
    fieldDriverFee: 200000,
    fieldPayrollStatus: 'paid',
    photographerId: 'w-photo-2',
    photographerName: 'Fajar Snap (Freelance)',
    photographerStatus: 'external',
    photographerFee: 250000,
    photographerPayrollStatus: 'paid',
    photoAlbumUrl: 'https://drive.google.com/drive/folders/panorama-majubersama-a',
    itineraryTemplateId: 'tmpl-bromo-sunrise',
    itineraryTemplateName: 'Bromo Sunrise Classic 4 Spot',
    itinerary: [
      { id: 'it-19', time: '01:30 WIB', title: 'Shuttle Stasiun Malang ke Pos Jeep', location: 'Stasiun Kota Baru', description: 'Penjemputan rombongan A', operationalCost: 50000, costNote: 'BBM Shuttle' },
      { id: 'it-20', time: '04:30 WIB', title: 'Sunrise Spot Penanjakan', location: 'Penanjakan 1', description: 'Sunrise bersama tim', operationalCost: 120000, costNote: 'Tiket TNBTS 6 Pax' }
    ],
    operationalCost: 170000,
    tripStatus: 'completed',
    updatedAt: '2026-09-16T11:00:00Z',
  },
  {
    id: 'trip-07',
    code: 'PNR-260916-03',
    date: '2026-09-16',
    timeSlot: '03:30 WIB (Sunrise)',
    tourPackage: 'Bromo Sunrise Classic 4 Spot',
    pickupPoint: 'Stasiun Kota Baru Malang',
    guestName: 'PT. Maju Bersama Outing (Group B)',
    guestCount: 6,
    guestPhone: '0812-4433-2212',
    agencyId: 'ag-2',
    agencyName: 'Bali Nusa Tourindo',
    packagePrice: 1350000,
    agencyPaymentStatus: 'paid',
    jeepDriverId: 'w-jeep-3',
    jeepDriverName: 'Joko Waluyo (Mitra Luar)',
    jeepUnit: 'Jeep 12 (Hardtop N 9921 KL)',
    jeepStatus: 'external',
    jeepFee: 300000,
    jeepPayrollStatus: 'paid',
    fieldDriverId: 'w-field-1',
    fieldDriverName: 'Rian Hidayat',
    fieldDriverStatus: 'internal',
    fieldDriverFee: 175000,
    fieldPayrollStatus: 'paid',
    photographerId: 'w-photo-1',
    photographerName: 'Dimas Anggara',
    photographerStatus: 'internal',
    photographerFee: 200000,
    photographerPayrollStatus: 'paid',
    photoAlbumUrl: 'https://drive.google.com/drive/folders/panorama-majubersama-b',
    itineraryTemplateId: 'tmpl-bromo-sunrise',
    itineraryTemplateName: 'Bromo Sunrise Classic 4 Spot',
    itinerary: [
      { id: 'it-21', time: '01:30 WIB', title: 'Shuttle Stasiun Malang ke Pos Jeep', location: 'Stasiun Kota Baru', description: 'Penjemputan rombongan B', operationalCost: 50000, costNote: 'BBM Shuttle' },
      { id: 'it-22', time: '04:30 WIB', title: 'Sunrise Spot Penanjakan', location: 'Penanjakan 1', description: 'Sunrise bersama tim', operationalCost: 120000, costNote: 'Tiket TNBTS 6 Pax' }
    ],
    operationalCost: 170000,
    tripStatus: 'completed',
    updatedAt: '2026-09-16T11:00:00Z',
  },

  // UPCOMING TRIPS (2026-09-18)
  {
    id: 'trip-08',
    code: 'PNR-260918-01',
    date: '2026-09-18',
    timeSlot: '03:30 WIB (Sunrise)',
    tourPackage: 'Bromo Sunrise Premium + Breakfast Piknik',
    pickupPoint: 'Hotel Lava View Sukapura',
    guestName: 'Bpk. Dr. Andre Pratama & Kolega',
    guestCount: 5,
    guestPhone: '0813-7766-5544',
    agencyId: 'ag-3',
    agencyName: 'Java Heritage Travel',
    packagePrice: 1450000,
    agencyPaymentStatus: 'unpaid',
    jeepDriverId: 'w-jeep-1',
    jeepDriverName: 'Budi Santoso',
    jeepUnit: 'Jeep 01 (Hardtop N 1045 AB)',
    jeepStatus: 'internal',
    jeepFee: 250000,
    jeepPayrollStatus: 'unpaid',
    fieldDriverId: 'w-field-1',
    fieldDriverName: 'Rian Hidayat',
    fieldDriverStatus: 'internal',
    fieldDriverFee: 175000,
    fieldPayrollStatus: 'unpaid',
    photographerId: 'w-photo-1',
    photographerName: 'Dimas Anggara',
    photographerStatus: 'internal',
    photographerFee: 200000,
    photographerPayrollStatus: 'unpaid',
    itineraryTemplateId: 'tmpl-bromo-sunrise',
    itineraryTemplateName: 'Bromo Sunrise Premium + Breakfast Piknik',
    itinerary: [
      { id: 'it-23', time: '03:30 WIB', title: 'Penjemputan Hotel Lava View', location: 'Lava View Lodge', description: 'Persiapan sarapan piknik', operationalCost: 0 },
      { id: 'it-24', time: '04:30 WIB', title: 'Sunrise Spot VIP Penanjakan 1', location: 'Penanjakan 1', description: 'Sunrise & kopi hangat', operationalCost: 120000, costNote: 'Tiket Masuk TNBTS 5 Pax' },
      { id: 'it-25', time: '07:30 WIB', title: 'Breakfast Piknik di Savana', location: 'Lembah Jemplang', description: 'Sarapan di meja lipat outdoor', operationalCost: 50000, costNote: 'Perlengkapan Meja & BBM' }
    ],
    operationalCost: 170000,
    tripStatus: 'booked',
    updatedAt: '2026-09-17T08:00:00Z',
  },
  {
    id: 'trip-09',
    code: 'PNR-260918-02',
    date: '2026-09-18',
    timeSlot: '03:30 WIB (Sunrise)',
    tourPackage: 'Bromo Sunrise 4 Spot',
    pickupPoint: 'Whiz Capsule Grand Bromo',
    guestName: 'Kim Min-seo Tour (Korea 4 Pax)',
    guestCount: 4,
    guestPhone: '+82 10 9988 7766',
    agencyId: 'ag-1',
    agencyName: 'Bromo Sunrise Discovery',
    packagePrice: 1250000,
    agencyPaymentStatus: 'unpaid',
    jeepDriverId: 'w-jeep-2',
    jeepDriverName: 'Pak Slamet Riyadi',
    jeepUnit: 'Jeep 04 (Hardtop N 7182 XY)',
    jeepStatus: 'internal',
    jeepFee: 250000,
    jeepPayrollStatus: 'unpaid',
    fieldDriverId: 'w-field-2',
    fieldDriverName: 'Agus Setiawan (Sewa)',
    fieldDriverStatus: 'external',
    fieldDriverFee: 200000,
    fieldPayrollStatus: 'unpaid',
    photographerId: 'w-photo-2',
    photographerName: 'Fajar Snap (Freelance)',
    photographerStatus: 'external',
    photographerFee: 250000,
    photographerPayrollStatus: 'unpaid',
    itineraryTemplateId: 'tmpl-bromo-sunrise',
    itineraryTemplateName: 'Bromo Sunrise 4 Spot',
    itinerary: [
      { id: 'it-26', time: '03:30 WIB', title: 'Penjemputan Whiz Capsule', location: 'Whiz Capsule Bromo', description: 'Bahasa inggris/korea dasar', operationalCost: 0 },
      { id: 'it-27', time: '04:30 WIB', title: 'Sunrise Bukit Cinta', location: 'Bukit Cinta', description: 'Golden sunrise', operationalCost: 100000, costNote: 'Tiket TNBTS 4 Pax' },
      { id: 'it-28', time: '07:30 WIB', title: 'Laut Pasir & Kawah Bromo', location: 'Lautan Pasir', description: 'Foto jeep & trek kawah', operationalCost: 50000, costNote: 'BBM & Parkir' }
    ],
    operationalCost: 150000,
    tripStatus: 'booked',
    updatedAt: '2026-09-17T09:00:00Z',
  }
];
